(function(g){var window=this;var a$=function(a,b,c,d){var e=b.Gb();g.se(a.element,"ytp-suggestion-set",!!e.videoId);var h=b.ag();d=b.Oc(c,d?d:"mqdefault.jpg");var k=b instanceof g.NB?g.Tk(b.lengthSeconds):null,m=!!h,h=m&&"RD"==g.IE(h).type;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.P("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Fj(c),is_featured:e.ts,is_list:m,is_mix:h,background:d?"background-image: url("+d+")":""};b instanceof
g.LE&&(c.playlist_length=b.A);a.update(c)},b$=function(a){var b=g.T(a),c=b.experiments.$("video_wall_moving_thumbnails_autoplay"),d=b.experiments.$("video_wall_moving_thumbnails_hover"),c=c||d;
this.B=b.B&&!b.C;b=g.Ji||g.Fc?{style:"will-change: opacity"}:null;d={I:"img",V:"ytp-videowall-moving-thumbnail",T:{src:"{{moving_thumbnail}}"}};g.R.call(this,{I:"a",V:"ytp-videowall-still",T:{href:"{{url}}",target:this.B?"_blank":null,"aria-label":"{{watch}}","data-is-featured":"{{is_featured}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",V:"ytp-videowall-still-image",T:{style:"{{background}}"}},c?d:null,{I:"span",V:"ytp-videowall-still-featured-label",P:[g.P("YTP_FEATURED")]},
{I:"span",V:"ytp-videowall-still-info",P:[{I:"span",V:"ytp-videowall-still-info-bg",P:[{I:"span",V:"ytp-videowall-still-info-content",T:b,P:[{I:"span",V:"ytp-videowall-still-info-title",P:["{{title}}"]},{I:"span",V:"ytp-videowall-still-info-author",P:["{{author_and_views}}"]},{I:"span",V:"ytp-videowall-still-info-duration",P:["{{duration}}"]}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",V:"ytp-videowall-still-listlabel-icon"},g.P("YTP_PLAYLIST"),
{I:"span",V:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",P:["{{playlist_length}}"]},")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],P:[{I:"span",V:"ytp-videowall-still-listlabel-mix-icon"},g.P("YTP_MIX"),{I:"span",V:"ytp-videowall-still-listlabel-length",P:[" (50+)"]}]}]});this.b=a;this.o=null;this.N("click",this.AK);this.N("keypress",this.BK);c&&this.S(this.ra["ytp-videowall-moving-thumbnail"],"load",this.DK);g.T(a).experiments.$("player_interaction_logging")&&
(a=a.app.ca,g.pb(a.B,this),b=String(a.F++),this.element.setAttribute("data-visual-id",b),g.Ob(this,(0,g.x)(a.D,a,this)))},c$=function(a){if(5E5<g.Yw(a.b.app.ia)){var b=a.o.zj();
b&&a.update({moving_thumbnail:b})}},d$=function(a){g.VE.call(this,a,{I:"div",
fa:["ytp-thumbnail-overlay","ytp-channel-overlay"],P:[{I:"div",V:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"div",V:"ytp-thumbnail-overlay-curtain"}]})},e$=function(){g.R.call(this,["div",
"ytp-subscribe-card",["img","ytp-author-image",{src:"{{image}}"}],["div","ytp-subscribe-card-right",["div","ytp-author-name","{{author}}"],["div","html5-subscribe-button-container"]]])},f$=function(a){var b=g.T(a).experiments.$("moving_thumbnails_autonav"),c={I:"img",
V:"ytp-upnext-moving-thumbnail",T:{src:"{{moving_thumbnail}}"}},c={I:"div",V:"ytp-upnext",T:{"aria-label":"{{watch}}"},P:[{I:"div",V:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},b?c:null,{I:"div",V:"ytp-thumbnail-overlay-curtain"},{I:"span",V:"ytp-upnext-top",P:[{I:"span",V:"ytp-upnext-header",P:[g.P("YTP_PLAYLIST_UP_NEXT")]},{I:"span",V:"ytp-upnext-title",P:["{{title}}"]},{I:"span",V:"ytp-upnext-author",P:["{{author}}"]}]},{I:"a",V:"ytp-upnext-autoplay-icon",T:{href:"{{url}}"},P:[{I:"svg",
T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},P:[{I:"circle",V:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{I:"circle",V:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{I:"polygon",V:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{I:"span",V:"ytp-upnext-bottom",P:[{I:"span",
V:"ytp-upnext-cancel"},{I:"span",V:"ytp-upnext-paused",P:[g.P("YTP_AUTOPLAY_PAUSED_2")]}]},{I:"span",V:"ytp-upnext-close"}]};g.R.call(this,c);var d=this.ra["ytp-upnext-cancel"],c=this.ra["ytp-upnext-close"],e=new g.R({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:0,"aria-label":g.P("YTP_AUTOPLAY_CANCEL")},P:[g.P("YTP_CANCEL")]});g.H(this,e);e.N("click",this.Vs,this);e.Da(d);d=new g.R({I:"button",fa:["ytp-upnext-close-button","ytp-button"]});g.H(this,d);d.N("click",this.Vs,this);
d.Da(c);this.b=a;this.G=this.ra["ytp-svg-autoplay-ring"];this.C=this.B=this.o=this.A=null;this.D=new g.je(this.nj,5E3,this);g.H(this,this.D);this.F=0;this.S(this.ra["ytp-upnext-autoplay-icon"],"click",this.VF);this.Us();this.S(a,"autonavvisibility",this.Us);b&&this.S(this.ra["ytp-upnext-moving-thumbnail"],"load",this.fM)},Ava=function(a,b){a.A=b;
a$(a,b,g.T(a.b),"hqdefault.jpg");g.qe(a.element,"ytp-moving-thumbnail-loaded");a.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});5E5<g.Yw(a.b.app.ia)&&(b=a.A.zj())&&a.update({moving_thumbnail:b})},g$=function(a){a.o||(g.Bl("a11y-announce",g.P("YTP_PLAYLIST_UP_NEXT")+" "+a.A.title),a.F=(0,g.rk)(),a.o=new g.je(a.Cl,25,a),a.Cl());
g.qe(a.element,"ytp-upnext-autoplay-paused")},i$=function(a){h$(a);
a.F=(0,g.rk)();a.Cl();g.K(a.element,"ytp-upnext-autoplay-paused")},h$=function(a){a.o&&(a.o.dispose(),a.o=null)},j$=function(a,b){g.TE.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.b=a;this.K=!1},k$=function(a){a=g.T(a);
return a.Zd&&!a.la},l$=function(a,b){j$.call(this,a,"videowall-endscreen");
this.ba=a;this.Z=b;this.F=0;this.o=[];this.G=this.C=this.B=null;this.H=this.U=!1;this.D=new g.Kq(this);g.H(this,this.D);this.J=new g.je(g.ra(g.K,this.element,"ytp-show-tiles"),0);g.H(this,this.J);b=new g.R({I:"button",fa:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.P("YTP_PREVIOUS")},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 32 32",width:"100%"},P:[{I:"path",T:{d:"M 19.41,20.09 14.83,15.5 19.41,10.91 18,9.5 l -6,6 6,6 z",fill:"#fff"}}]}]});g.H(this,b);b.Da(this.element);
b.N("click",this.pE,this);this.L=new g.Lk({I:"div",V:"ytp-endscreen-content"});g.H(this,this.L);this.L.Da(this.element);b=new g.R({I:"button",fa:["ytp-button","ytp-endscreen-next"],T:{"aria-label":g.P("YTP_NEXT")},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 32 32",width:"100%"},P:[{I:"path",T:{d:"m 12.59,20.34 4.58,-4.59 -4.58,-4.59 1.41,-1.41 6,6 -6,6 z",fill:"#fff"}}]}]});g.H(this,b);b.Da(this.element);b.N("click",this.yK,this);this.A=new f$(a);g.H(this,this.A);g.Lp(this.b,this.A.element,
4);this.sa()},m$=function(a){return(0,g.S)(a.H,function(a){return g.UE(a)})},n$=function(a,b,c){return 0==b&&a.B.length&&(b=c/l$.b,2<=c/l$.b&&2<=b&&g.T(a.b).experiments.$("video_wall_emphasize_first"))?2*l$.b:l$.b},o$=function(a){var b=a.Z.So();
b!=a.U&&(a.U=b,a.b.Za("autonavvisibility"))},p$=function(a){j$.call(this,a,"subscribecard-endscreen");
this.o=new d$(a);g.H(this,this.o);g.Lp(this.b,this.o.element,4);this.A=new e$;g.H(this,this.A);this.sa()},q$=function(a){g.SE.call(this,a);
g.vi({});this.g=null;this.isAvailable=!0;this.o=new g.Kq(this);g.H(this,this.o);this.A=g.T(a);k$(a)?this.g=new l$(this.b,this):this.A.la?this.g=new p$(this.b):this.g=new j$(this.b);g.H(this,this.g);g.Lp(this.b,this.g.element,4);this.nu();this.o.S(a,"videodatachange",this.nu,this);this.o.S(a,"crn_endscreen",this.oK,this);this.o.S(a,"crx_endscreen",this.pK,this)};
g.z(b$,g.R);g.f=b$.prototype;g.f.nf=function(){var a=this.o.Gb().videoId;g.E8(this.b.app,a,this.o.Dc,this.o.ag(),void 0,void 0)};
g.f.AK=function(a){g.GD(this.b,this);g.Tl(a,this.b,!this.b.isFullscreen()&&this.B,this.o.Dc)&&this.nf()};
g.f.CK=function(){this.ya(this.A);this.A=null;c$(this)};
g.f.BK=function(a){switch(a.keyCode){case 13:case 32:g.Cj(a)||(this.nf(),g.Bj(a))}};
g.f.DK=function(a){120<g.xj(a).naturalWidth&&g.K(this.element,"ytp-videowall-moving-thumbnail-loaded")};
g.z(d$,g.VE);d$.prototype.rb=function(a){a?this.A.show():g.hp(this.A)};
g.z(e$,g.R);g.z(f$,g.R);g.f=f$.prototype;g.f.nj=function(){this.B&&(this.D.stop(),this.ya(this.C),this.C=null,this.B.close(),this.B=null)};
g.f.Us=function(){this.rb(g.oD(this.b))};
g.f.MF=function(){window.focus();this.nj()};
g.f.Cl=function(){var a=g.T(this.b).experiments.b("autoplay_time")||1E4,b=Math.min((0,g.rk)()-this.F,a),a=Math.min(b/a,1);this.G.setAttribute("stroke-dashoffset",-293*(a+1));1<=a?this.select(!0):this.o&&this.o.start()};
g.f.select=function(a){var b=g.T(this.b);if(b.experiments.$("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.bp(this.b,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.A.Gb(),this.nj(),this.B=new window.Notification(g.P("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Oc(b)}),this.C=this.S(this.B,"click",this.MF),this.D.start())}h$(this);b=this.A.Gb().videoId;
g.E8(this.b.app,b,a?this.A.Yu:this.A.Dc,this.A.ag(),void 0,void 0)};
g.f.VF=function(a){!g.Cj(a)&&g.Uk(a)&&(this.select(),g.Bj(a))};
g.f.Vs=function(a){g.Bj(a);g.xD(this.b,"autonavcancel");g.qD(this.b,!0)};
g.f.fM=function(a){120<g.xj(a).naturalWidth&&g.K(this.element,"ytp-moving-thumbnail-loaded")};
g.f.R=function(){h$(this);this.nj();f$.M.R.call(this)};
g.z(j$,g.TE);j$.prototype.create=function(){this.K=!0};
j$.prototype.destroy=function(){this.K=!1};
j$.prototype.Il=function(){return!1};
g.z(l$,j$);l$.b=2;g.f=l$.prototype;g.f.create=function(){l$.M.create.call(this);var a=this.b.getVideoData();a&&(this.B=m$(a),this.C=a);this.zf();this.D.S(this.b,"appresize",this.zf);this.D.S(this.b,"videodatachange",this.zK);this.D.S(this.b,"autonavchange",this.hw);this.D.S(this.b,"autonavcancel",this.xK);this.D.S(this.element,"transitionend",this.YG)};
g.f.destroy=function(){g.Mq(this.D);g.Qb(this.o);this.o=[];this.B=null;l$.M.destroy.call(this);g.qe(this.element,"ytp-show-tiles");this.J.stop()};
g.f.Il=function(){return 1!=this.C.autonavState};
g.f.mi=function(){return g.FD(this.b)&&this.Il()&&!this.G};
g.f.show=function(){l$.M.show.call(this);g.qe(this.element,"ytp-show-tiles");g.T(this.b).isMobile?g.ke(this.J):this.J.start();(this.H||this.G&&this.G!=this.C.clientPlaybackNonce)&&g.qD(this.b,!1);var a=this.mi();g.FD(this.b)&&g.T(this.b).experiments.$("ui_logging")&&this.Z.log({cancelButtonShow:a?"1":"0",state:this.Il()?"enabled":"disabled"});a?(o$(this),2==this.C.autonavState?g.T(this.b).experiments.$("fast_autonav_in_background")&&3==this.b.getVisibilityState()?this.A.select(!0):g$(this.A):3==this.C.autonavState&&
i$(this.A)):(g.qD(this.b,!0),o$(this))};
g.f.sa=function(){l$.M.sa.call(this);i$(this.A);o$(this)};
g.f.YG=function(a){g.xj(a)==this.element&&this.zf()};
g.f.zf=function(){if(this.B&&this.B.length){var a=g.T(this.b).experiments.$("video_wall_moving_thumbnails_hover");g.K(this.element,"ytp-endscreen-paginate");for(var b=g.mn(this.element),c=b.width/b.height,d=96/54,e=l$.b,h=l$.b,k=Math.max(b.width/96,2),m=Math.max(b.height/54,2),l=this.B.length,p=Math.pow(l$.b,2),t=l*p,u=n$(this,0,m),y=n$(this,1,m),t=t+(Math.pow(u,2)-p),t=t+(Math.pow(y,2)-p),t=t-p;0<t&&(e<k||h<m);){var I=e/l$.b,E=h/l$.b,M=e<=k-l$.b&&t>=E*p,la=h<=m-l$.b&&t>=I*p;if((I+1)/E*d/c>c/(I/(E+
1)*d)&&la)t-=I*p,h+=l$.b;else if(M)t-=E*p,e+=l$.b;else if(la)t-=I*p,h+=l$.b;else break}d=!1;k=l$.b+u;t>=3*p&&6>=l*p-t&&(h>=k||e>=k)&&y<=l$.b&&(d=!0);t=96*e;p=54*h;c=t/p<c?b.height/p:b.width/t;c=Math.min(c,2);t*=c;p*=c;t*=g.gf(b.width/t||1,1,1.21);p*=g.gf(b.height/p||1,1,1.21);t=Math.floor(Math.min(b.width,t));p=Math.floor(Math.min(b.height,p));b=this.L.element;g.ln(b,t,p);g.Vm(b,{marginLeft:t/-2+"px",marginTop:p/-2+"px"});Ava(this.A,this.B[0]);g.se(this.element,"ytp-endscreen-takeover",this.mi());
o$(this);c=t+4;t=p+4;p=0;k=!this.mi();m=!1;for(I=0;I<e;I++)for(E=0;E<h;E++)if(M=y>l$.b&&1<=p&&!m?p+1:p,la=0,d&&I>=e-l$.b&&E>=h-l$.b?la=1:0==E%l$.b&&0==I%l$.b&&(E<u&&I<u?0==E&&0==I&&(la=u):y>l$.b&&E>=h-y&&I>=e-y?E==h-y&&I==e-y&&(m=!0,M=1,la=y):la=l$.b),M=(M+this.F)%l,M=0>M*l?M+l:M,0!=la){var wa=this.o[p];wa||(wa=new b$(this.b),this.o[p]=wa,b.appendChild(wa.element));var Ia=Math.floor(t*E/h),$a=Math.floor(c*I/e),ie=Math.floor(t*(E+la)/h)-Ia-4,td=Math.floor(c*(I+la)/e)-$a-4;g.an(wa.element,$a,Ia);g.ln(wa.element,
td,ie);g.Vm(wa.element,"transitionDelay",(E+I)/20+"s");g.se(wa.element,"ytp-videowall-still-mini",1==la);g.se(wa.element,"ytp-videowall-still-large",2<la);la=wa;M=this.B[M];wa=k&&!a;la.o=M;Ia=g.T(la.b);a$(la,M,Ia,g.ne(la.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");g.qe(la.element,"ytp-videowall-moving-thumbnail-loaded");la.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});wa?(g.K(la.element,"ytp-videowall-active"),
c$(la)):Ia.experiments.$("video_wall_moving_thumbnails_hover")&&!la.A&&(la.A=la.N("mouseover",la.CK));Ia=M.Dc;wa=la.b;M=la;Ia=Ia&&Ia.itct;g.T(wa).experiments.$("player_interaction_logging")&&(la=wa.app.ca,wa=Ia,M=M.element.getAttribute("data-visual-id"),g.HD(la,"onLogServerVeCreated",{id:M,tracking_params:wa}));p++}g.se(this.element,"ytp-endscreen-paginate",p<l);for(a=this.o.length-1;a>=p;a--)wa=this.o[a],g.Of(wa.element),g.Pb(wa);this.o.length=p}};
l$.o=2;l$.g=1.21;g.f=l$.prototype;g.f.zK=function(){var a=this.b.getVideoData();this.C!=a&&(this.F=0,this.B=m$(a),this.C=a,this.zf())};
g.f.yK=function(){this.F+=this.o.length;this.zf()};
g.f.pE=function(){this.F-=this.o.length;this.zf()};
g.f.PC=function(){return!!this.A.o};
g.f.hw=function(a){1==a?(this.H=!1,this.G=this.C.clientPlaybackNonce,h$(this.A),this.g&&this.zf()):(this.H=!0,this.g&&this.mi()&&(2==a?g$(this.A):3==a&&i$(this.A)))};
g.f.xK=function(a){if(a){for(a=0;a<this.o.length;a++)g.ID(this.ba,this.o[a],!0);this.hw(1)}else this.G=null,this.H=!1;this.zf()};
g.z(p$,j$);p$.prototype.create=function(){p$.M.create.call(this);g.Mf(this.element);this.A.Da(this.element);var a=this.b.getVideoData().videoId;a&&(a=g.Du(g.T(this.b),a,!0),g.Gk(a,{method:"GET",xb:this.B,context:this,Zz:!0}))};
p$.prototype.B=function(a,b){if(this.K){a=b.user_info;b=a.channel_banner_url;g.Cu.test(b)||(b="");var c=a.channel_logo_url||a.image_url;g.Cu.test(c)||(c="");this.o.za("background",b?"background-image: url("+b+")":"");this.A.za("image",c);this.A.za("author",a.channel_title||a.username);a=a.subscription_button_html;b=this.A.ra["html5-subscribe-button-container"];a?b.innerHTML=g.Ve(a):g.Mf(b)}};
p$.prototype.show=function(){p$.M.show.call(this);this.o.rb(!0)};
p$.prototype.sa=function(){p$.M.sa.call(this);this.o.rb(!1)};
g.z(q$,g.SE);g.f=q$.prototype;g.f.cw=function(){var a=this.b.getVideoData(),b=!k$(this.b)||!(!a.H||!a.H.length),a=g.Lm(a,"ypc_module"),c=g.n5(this.b.app);return(b||!1)&&!a&&!c};
g.f.So=function(){return(this.g instanceof l$||!1)&&this.g.g&&this.g.mi()};
g.f.NC=function(){return this.So()?this.g.PC():!1};
g.f.R=function(){var a=this.b;g.ej(a.app,"endscreen",a.playerType);q$.M.R.call(this)};
g.f.load=function(){q$.M.load.call(this);this.g.show();g.T(this.b).la&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.f.log=function(a){g.bp(this.b,"end",a)};
g.f.unload=function(){q$.M.unload.call(this);this.g.sa();this.g.destroy();this.isAvailable=!1};
g.f.oK=function(a){this.cw()&&(this.g.K||this.g.create(),"load"==a.getId()&&this.load())};
g.f.pK=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.f.nu=function(){var a=this.b;g.ej(a.app,"endscreen",a.playerType);var a=Math.max(1E3*(this.b.getVideoData().lengthSeconds-10),0),a=new g.aj(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.aj(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});this.b.tb([a,b])};
window._exportCheck==g.ua&&g.ba("yt.player.modules.EndScreenModule2",q$,void 0);})(_yt_player);
